# Generated by Django 4.2.15 on 2025-09-10 10:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="begraafplaats",
            name="id_productie",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
