repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
      - id: check-yaml
        exclude: ^(frontend/|backend/apps/profilr/templates/)
      - id: end-of-file-fixer
        exclude: ^(frontend/|backend/apps/profilr/templates/)
      - id: trailing-whitespace
        exclude: ^(frontend/|backend/apps/profilr/templates/)
      - id: detect-private-key
        exclude: ^(frontend/|backend/apps/profilr/templates/)
  -   repo: https://github.com/humitos/mirrors-autoflake.git
      rev: v1.3
      hooks:
      - id: autoflake
        exclude: ^(frontend/|backend/apps/profilr/templates/)
        args: ['--in-place', '--remove-all-unused-imports', '--remove-unused-variable']
  -   repo: https://github.com/timothycrosley/isort
      rev: '5.12.0'
      hooks:
      - id: isort
        exclude: ^(frontend/|backend/apps/profilr/templates/)
  -   repo: https://github.com/ambv/black
      rev: '22.12.0'
      hooks:
      - id: black
        language_version: python3
        exclude: ^(frontend/|backend/apps/profilr/templates/)
  -   repo: https://github.com/pycqa/flake8
      rev: '6.0.0'
      hooks:
      - id: flake8
        exclude: ^(frontend/|backend/apps/profilr/templates/)
