version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - .env.test
    volumes:
      - ./backend:/app
    depends_on:
      - redis
    networks:
      - mor_network
    command: ["bash", "/app/deploy/docker-entrypoint.development.sh"]

  redis:
    image: redis
    networks:
      - mor_network
    ports:
      - "6379:6379"

networks:
  mor_network:
    external: true
