version: '3'
services:
  app:
    build: ./app
    ports:
      - "8000:8000"
    env_file:
      - .env.local
    volumes:
      - ./app:/app
    depends_on:
      - redis
    networks:
      - mor_network
    command: ["bash", "/app/deploy/docker-entrypoint.development.sh"]

  redis:
    image: redis
    networks:
      - mor_network
    ports:
      - "6379:6379"

networks:
  mor_network:
    external: true
