version: '3'
services:
  gateway:
    container_name: mbc.mor.local
    build: ./nginx
    volumes:
      - ./nginx/nginx-default.development.conf:/etc/nginx/conf.d/default.conf
      - ./media:/media
    depends_on:
      mbc_app:
        condition: service_started
    ports:
      - 8001:8001
    networks:
      - mor_bridge_network
    env_file:
      - .env.local
  mbc_app:
    build: ./app
    env_file:
      - .env.local
    volumes:
      - ./app:/app
      - ./media:/media
    depends_on:
      redis:
        condition: service_started
      database:
        condition: service_healthy
    networks:
      - mbc_network
      - mor_bridge_network
    command: ["bash", "/app/deploy/docker-entrypoint.development.sh"]
    restart: always

  redis:
    image: redis
    networks:
      - mbc_network
    ports:
      - "6379"

  database:
    image: postgis/postgis:11-3.3
    shm_size: '1024m'
    ports:
      - "7999:5432"
    env_file:
      - .env.local
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - mbc_network

volumes:
  postgres-data:

networks:
  mbc_network:
    external: true
  mor_bridge_network:
    external: true
