version: '3'
services:
  app:
    build: ./app
    ports:
      - "8000:8000"
    env_file:
      - .env.local
    volumes:
      - ./app:/app
    depends_on:
      - redis
      - database
    networks:
      - mbc_network
    command: ["bash", "/app/deploy/docker-entrypoint.development.sh"]

  redis:
    image: redis
    networks:
      - mbc_network
    ports:
      - "6379:6379"

  database:
    image: postgis/postgis:11-3.3
    shm_size: '1024m'
    ports:
      - "5411:5432"
    env_file:
      - .env.local
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - mbc_network

volumes:
  postgres-data:

networks:
  mbc_network:
    external: true
