# Generated by Django 3.2.16 on 2023-06-29 09:23

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Signaal",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("aangemaakt_op", models.DateTimeField(auto_now_add=True)),
                ("aangepast_op", models.DateTimeField(auto_now=True)),
                ("afgesloten_op", models.DateTimeField(blank=True, null=True)),
                ("meldingen_signaal_url", models.URLField(blank=True, null=True)),
                ("formulier_data", models.JSONField(default=dict)),
            ],
            options={
                "verbose_name": "Signaal",
                "verbose_name_plural": "Signalen",
                "ordering": ("-aangemaakt_op",),
            },
        ),
    ]
