# Generated by Django 3.2.16 on 2023-06-07 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("signalen", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="signaal",
            name="afgesloten_op",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
