# Generated by Django 3.2.16 on 2023-04-06 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Begraafplaats",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("naam", models.CharField(max_length=200)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                "verbose_name_plural": "Begraafplaatsen",
                "ordering": ("naam",),
            },
        ),
        migrations.CreateModel(
            name="Categorie",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("naam", models.CharField(max_length=200)),
                ("volgorde", models.IntegerField(default=0)),
                ("toon_andere_oorzaak", models.BooleanField(default=False)),
                (
                    "toon_specifiek_graf",
                    models.CharField(
                        choices=[
                            ("altijd", "Altijd tonen"),
                            (
                                "specifiek_graf",
                                "Alleen tonen als specifiek graf gekozen is",
                            ),
                            (
                                "niet_specifiek_graf",
                                "Alleen tonen als specifiek graf niet gekozen is",
                            ),
                        ],
                        default="altijd",
                        help_text="Toon deze categorie als kiest voor een specifiek graf",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Categorieën",
                "ordering": ("volgorde",),
            },
        ),
        migrations.CreateModel(
            name="Medewerker",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("naam", models.CharField(max_length=200)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "begraafplaatsen",
                    models.ManyToManyField(
                        related_name="medewerkers", to="mbc.Begraafplaats"
                    ),
                ),
            ],
            options={
                "ordering": ("naam",),
            },
        ),
    ]
