# Generated by Django 3.2.16 on 2023-05-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mbc", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="categorie",
            name="onderwerp",
            field=models.URLField(
                default="https://mor-core-acc.forzamor.nl/v1/onderwerp/overig/"
            ),
        ),
    ]
